FROM node:10.19.0-alpine as builder

RUN apk add --no-cache --update build-base

ENV APP_HOME /app/
WORKDIR $APP_HOME
COPY package.json package-lock.json $APP_HOME

RUN npm install

COPY . .

RUN npm run build

# Production container
FROM nginx:1.17.8-alpine

WORKDIR /app/

COPY --from=builder /app/dist/ /usr/share/nginx/html/
